### PR TITLE
Covert most chmod users to fchmod

### PR DESCRIPTION
**Pull request by xrmx**
The plan is to avoid toctouc races, i've converted the user where the fd of the path was nearly available. There are a couple of hooks which plays with chmod which may be hard to convert and chmod on cgroup dir in core/utils.c:222 which can be coverted with some code reordering. Please review.

### CODE REVIEW

**Comment by unbit** [comment]
I think it is "utopic" to aim at completely solving a problem that is intrinsic in UNIX :) Btw your patches are not invasive, and will not hurt for sure

**Comment by unbit** [comment]
It looks like fchmod on socket is not portable (or better, it looks like is reliable only on Linux), @xrmx can you change it for taking in account only files ?

**Comment by xrmx** [comment]
Commits on sockets are even more bogus because the fchmod must be called before bind otherwise it has no effect (reference: http://openvswitch.org/pipermail/discuss/2011-April/005073.html). So let's just revert the three socket commits. @unbit i can do and push the reverts if you are ok with that.

**Comment by unbit** [comment]
yes its ok

**Comment by xrmx** [comment]
Pushed the three reverts.

**Pull request merged**
