### PR TITLE
fix emperor SIGURG feature (cleanup blacklist)

### PR DESCRIPTION
**Pull request by Shir0kamii**
Hi,

@unbit told me about a SIGURG feature for emperor to clean its blacklist but it didn't work. Here is the fix I writed.

If i understand clearly, the previous code was taking the vassal list which does not contains blacklisted vassals. Now I simply take the blacklist and free all of its items.

I will also make a PR for the documentation.

### CODE REVIEW

**Comment by xrmx** [comment]
A commit message would be appreciated. Explaining why this fix things would be event better :)

**Comment by Shir0kamii** [comment]
I will do it right now, since I should have done it since the beginning !

**Comment by Shir0kamii** [comment]
@xrmx Any chance that you check this PR soon, to know if I have to make change to it ?

**Comment by unbit** [comment]
sorry for the late, i will review it during the week end

**Comment by unbit** [comment]
So, the bug is related to the fact that blacklisted instances are not listed in the healthy instances, so the cleanup procedure will never find a blacklisted record.

Your patch does the right thing, but you missed to reset emperor_blacklist as NULL

**Comment by Shir0kamii** [comment]
@unbit Sorry about forgetting that. It's done now.

**Pull request merged**
