### PR TITLE
support io.BytesIO with wsgi.file_wrapper

### LINKED ISSUE #1126: In python3, uwsgi fails to respond a stream from BytesIO object.
in python3, uwsgi fails to respond a BytesIO stream.

If I use the following falcon application in test.py:

``` python
import falcon
import io

class Resource(object):
    def on_get(self, req, resp):
        resp.stream = io.BytesIO(b'moshe')

api = falcon.API()
api.add_route('/', Resource())
application = api
```

When I run (python3 uwsgi): `uwsgi --http :8000 --module test` and curl it `curl http://localhost:8000`, the client gets an error `curl: (52) Empty reply from server` and uwsgi log shows: 

```
*** Starting uWSGI 2.0.11.2 (64bit) on [Thu Dec 10 13:45:07 2015] ***
compiled with version: 5.1.1 20150618 (Red Hat 5.1.1-4) on 10 December 2015 12:41:16
os: Linux-4.2.6-300.fc23.x86_64 #1 SMP Tue Nov 10 19:32:21 UTC 2015
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/eyal/work/hammock
detected binary path: /home/eyal/work/hammock/.tox/py35/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 30621
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 7
spawned uWSGI http 1 (pid: 4212)
uwsgi socket 0 bound to TCP address 127.0.0.1:42015 (port auto-assigned) fd 6
Python version: 3.5.0 (default, Dec 10 2015, 11:41:08)  [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x285da00
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x285da00 pid: 4211 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 4211, cores: 1)
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eyal/work/hammock/.tox/py35/lib/python3.5/site-packages/falcon/api.py", line 232, in __call__
    body = self._get_body(resp, env.get('wsgi.file_wrapper'))
  File "/home/eyal/work/hammock/.tox/py35/lib/python3.5/site-packages/falcon/api.py", line 653, in _get_body
    return wsgi_file_wrapper(stream, self._STREAM_BLOCK_SIZE)
SystemError: <built-in function uwsgi_sendfile> returned a result with an error set
[pid: 4211|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 303 bytes} [Thu Dec 10 13:45:11 2015] GET / => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

when I run the same app with gunicorn (in python 3 enivornment): `gunicorn test:application`, The curl returns 'moshe'.

### PR DESCRIPTION
**Pull request by awelzel**
Proposal to fix #1126 - commit  10e3f05 has a few details in the commit message.

There's also a related improvement that when an application yields a non-bytes object, uwsgi will log this as an error.

### CODE REVIEW

**Comment by rdeioris** [comment]
hi @awelzel i have reviewed the patch. Can you re-add the sendfile_obj to uwsgi.h to maintain ABI compatibility ?

**Comment by rdeioris** [comment]
@xrmx after the fix it should be safe for backport

**Comment by awelzel** [comment]
Hey @rdeioris , thanks for checking it out. I have just repushed it without the last commit which removed the `sendfile_obj`.

**Comment by awelzel** [comment]
@xrmx - didn't see this in `uwsgi-2.0` - probably too scary?

**Comment by xrmx** [comment]
@awelzel more like i missed it :)

**Comment by xrmx** [comment]
Merged btw

**Comment by MaicoTimmerman** [comment]
Any indication when this fix will hit a release? Latest release was in februari and we're really looking forward to this fix.

**Comment by kbehlers** [comment]
@MaicoTimmerman seems to have been released with [2.0.19](https://github.com/unbit/uwsgi-docs/blob/master/Changelog-2.0.19.rst)

**Pull request merged**
