### PR TITLE
php7 build fix, don't forget to add "default php" as plugin name while b...

### PR DESCRIPTION
**Pull request by mow**
php7 build fix, don't forget to add "default php" as plugin name while building, otherwise an "undefined symbol" error raises (UWSGICONFIG_PHPDIR=/opt/php7 python uwsgiconfig.py --plugin plugins/phpng default php)

### CODE REVIEW

**Comment by unbit** [comment]
Hi, instead of adding plugins to the core repository we prefer to split them in different repository. Feel free to create a uwsgi-phpng one and we will add it to the official site.

Remember that the new (robust) way of building plugins is

```sh
uwsgi --build-plugin <dir>
```

**Comment by mow** [comment]
Thank you for fast response :)

**Comment by mow** [comment]
Hi again, here is the separate repository https://github.com/mow/uwsgi-php7

**Comment by unbit** [comment]
Great, starred and spammed on twitter :)

**Comment by mow** [comment]
:D thanks

**Pull request closed without merging**
