### PR TITLE
Harakiri: Graceful termination + queue threshold

### PR DESCRIPTION
**Pull request by filipenf**
Backgound:
-
Harakiri is often used to prevent slow requests from taking too much capacity. One drawback is the fact that the `SIGKILL` doesn't allow for the application to cleanly shutdown - this is a problem for observability: libraries like `jaeger`, `sentry`, `datadog`, etc don't get a chance to push tracing data back so it is hard to tell what exactly is going on during that specific request

Proposed changes:
-
This pull request extends harakiri with 3 new options:
- `harakiri-graceful-timeout` additional timeout for the worker to attempt a graceful shutdown. The application can catch the termination signal and perform an "emergency shutdown"
- `harakiri-graceful-signal` determines which signal should be used (default `SIGTERM`)
- `harakiri-graceful-queue-threshold` only triggers a harakiri if/when the listen queue crosses a threshold. Harakiri continues to be checked until the conditions are met

The changes are backwards compatible: If none of those options are used, harakiri will immediately invoke a `SIGKILL`

Testing:
-

To test it I added a simple python app that registers a handler for `SIGSYS` (31), in which it prints a line and just calls `exit()`. Then an exit handler sleeps for 3 seconds so if the `harakiri-graceful-timeout` is < 3 it will be killed

Tested with:
```
$ ./uwsgi --master --http :8080 --harakiri 1 --wsgi-file tests/harakiri.py --harakiri-graceful-timeout 1 --py-call-osafterfork --lazy-apps --enable-threads --threads 2 --harakiri-graceful-signal 31
```

```
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55a86e18ddf0 pid: 585212 (default app)
[Python App] sleeping
Mon May 17 22:17:34 2021 - *** HARAKIRI ON WORKER 1 (pid: 585212, try: 1, graceful: yes) ***
Mon May 17 22:17:34 2021 - HARAKIRI !!! worker 1 status !!!
Mon May 17 22:17:34 2021 - HARAKIRI [core 0] 127.0.0.1 - GET / since 1621315052
Mon May 17 22:17:34 2021 - HARAKIRI !!! end of worker 1 status !!!
Mon May 17 22:17:34 2021 - HARAKIRI triggered by worker 1 core 0 !!!
[Python App] attempting graceful shutdown triggered by harakiri (signal 31)
Mon May 17 22:17:35 2021 - *** HARAKIRI ON WORKER 1 (pid: 585212, try: 2, graceful: no) ***
Mon May 17 22:17:35 2021 - HARAKIRI !!! worker 1 status !!!
Mon May 17 22:17:35 2021 - HARAKIRI [core 0] 127.0.0.1 - GET / since 1621315052
Mon May 17 22:17:35 2021 - HARAKIRI !!! end of worker 1 status !!!
Mon May 17 22:17:35 2021 - HARAKIRI triggered by worker 1 core 0 !!!
DAMN ! worker 1 (pid: 585212) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 585268)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55a86e18ddf0 pid: 585268 (default app)
```

repeating the test with a longer graceful timeout, the app shuts down correctly (ie `exiting now` shows up in the output):

```
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55667ddbde10 pid: 627092 (default app)
[Python App] sleeping
Tue May 18 17:06:47 2021 - *** HARAKIRI ON WORKER 1 (pid: 627092, try: 1, graceful: yes) ***
Tue May 18 17:06:47 2021 - HARAKIRI !!! worker 1 status !!!
Tue May 18 17:06:47 2021 - HARAKIRI [core 0] 127.0.0.1 - GET / since 1621382805
Tue May 18 17:06:47 2021 - HARAKIRI !!! end of worker 1 status !!!
Tue May 18 17:06:47 2021 - HARAKIRI triggered by worker 1 core 0 !!!
[Python App] attempting graceful shutdown triggered by harakiri (signal 31)
[Python App] exiting now
DAMN ! worker 1 (pid: 627092) died :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 627124)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55667ddbde10 pid: 627124 (default app)
```
without any of the new options:

```
[Python App] sleeping
Tue May 25 17:43:17 2021 - *** HARAKIRI ON WORKER 1 (pid: 60593, try: 1, graceful: yes) ***
Tue May 25 17:43:17 2021 - HARAKIRI !!! worker 1 status !!!
Tue May 25 17:43:17 2021 - HARAKIRI [core 0] 127.0.0.1 - GET / since 1621989796
Tue May 25 17:43:17 2021 - HARAKIRI !!! end of worker 1 status !!!
Tue May 25 17:43:17 2021 - HARAKIRI triggered by worker 1 core 0 !!!
DAMN ! worker 1 (pid: 60593) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 60612)
```

### CODE REVIEW

**Comment by rdi-mindesk** [comment]
@xrmx i think it makes sense: unless the worker is seriously stuck, the TERM signal handler should kick in allowing the worker to do some form of cleanup. But maybe it would be better to allow the user to choose which signal to trigger (to differentiate between an emergency and a normal shutdown). @filipenf thanks for the pull request btw. I think it is worth to discuss it.

**Comment by filipenf** [comment]
@rdi-mindesk glad to hear that there's interest. I was thinking the same about the signal, the application developer may want to use a custom signal to implement the termination logic. I'll add some tests

**Comment by filipenf** [comment]
btw I've added `harakiri-graceful-signal` and a test python app `harakiri.py` to confirm the behavior with graceful-harakiri works as expected and that it did not change the previous behavior when the new flag is absent

**Comment by filipenf** [comment]
@xrmx does this change make sense to you? I'd appreciate your feedback

**Comment by wojcikm** [comment]
Any chances to merge this PR soon?

**Comment by filipenf** [comment]
fwiw we are using this in production at my company for a few months. It has been very helpful to identify production issues when harakiri starts happening we now have traces for the killed requests which helps us to identify backend problems way more quickly.

We're running out of a fork I made a while ago: https://pypi.org/project/nuwsgi/ but I'd prefer to eventually switch back to mainstream if/wehn it gets merged 🙏🏽

**Comment by zeldrinn** [comment]
good work @filipenf! would be awesome to get this merged, we're running into the same issues with tracing, etc.

**Comment by xrmx** [comment]
I'm working on getting this merged, I've rebased @filipenf change against master here https://github.com/unbit/uwsgi/pull/2523, will rebase this later once that is in.

**Comment by xrmx** [comment]
Fixed indentation, moved uwsgi_server changes to the end of struct to keep backward compatibility, rework commit message a bit. We can tidy any eventual issue that will come up later, thanks a lot @filipenf!

**Comment by zeldrinn** [comment]
thank you @xrmx @filipenf!!!

**Comment by xrmx** [comment]
To anyone keen to give it a run I've uploaded a uwsgi 2.0.22 test release at https://test.pypi.org/project/uWSGI/

**Comment by Liubey** [comment]
@xrmx Hi, Is there any plan to release it at pypi(not test release)?

**Pull request merged**
