### PR TITLE
Added default for expanding env vars

### LINKED ISSUE #1604: fallback or default for expanding environment variables?
hi, I was looking through the [parsing order documentation](http://uwsgi-docs.readthedocs.io/en/latest/ParsingOrder.html#expanding-variables-placeholders) and I wasn't able to find this. can I give a fallback or default if environment variable isn't set?

```
[uwsgi]
http = :$(PORT:-5000)
```

I want to add the `:5000` part at the end. is this possible?

thanks!

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
This should resolve #1604

### CODE REVIEW

**Comment by unbit** [comment]
Thanks.

**Comment by eatonphil** [comment]
Unless I'm mistaken this is not part of a release. When will this be released?

**Comment by hjpotter92** [comment]
Same point as @eatonphil , would love to use this asap.

Thanks

**Comment by Tomasz-Kluczkowski** [comment]
Is there any progress on this? Looks merged but not available :(...

**Comment by sshishov** [comment]
@unbit Could you please provide the approximate date of release for this feature?

**Pull request merged**
