### PR TITLE
plugins/python: PyOS_AfterFork_Child if available

### PR DESCRIPTION
**Pull request by luchr**
Attempt to fix [Issue 1813](/unbit/uwsgi/issues/1813).

### CODE REVIEW

**Comment by unbit** [comment]
Thanks

**Comment by gpjt** [comment]
Any guesses as to when this will be released?   Not trying to rush you, of course -- just need to know :-)

**Comment by xrmx** [comment]
Note to self: backport and fix whitespace.

**Comment by rdeioris** [comment]
i should be able to make a new release this sunday

**Pull request merged**
