### PR TITLE
don't close $env->{'psgix.io'} on "PSGI cancel"

### PR DESCRIPTION
**Pull request by jef-sure**
let application do it

### CODE REVIEW

**Comment by jef-sure** [comment]
With this patch I don't have to `dup()` socket before returning `[]`

**Comment by unbit** [comment]
in such a case if the dev forget to close the fd we will have a leak. It is how psgix.io is expected to work ?

**Comment by jef-sure** [comment]
I can't see any alternative. It's not so difficult to close the socket in DESTROY method of request, so this usually not a problem. When application takes care of the socket and protocol, it must control when it closes the socket.

**Comment by jef-sure** [comment]
When I have to `dup()` the socket -- I have the same "socket leak" problem.

**Pull request merged**
