### PR TITLE
fix include of "greenlet.h"

### PR DESCRIPTION
**Pull request by 2mf**
Fix include `greenlet.h`
#1100 
#1466

### CODE REVIEW

**Comment by xrmx** [comment]
Sorry, but I don't think we are going to bundle dependencies as git submodules.

**Comment by 2mf** [comment]
Please make a suggestion that is acceptable for you as a fix?

**Comment by xrmx** [comment]
The fix would be more smart if the greenlet.h is on a position we can find out, if it's not then there's something off with how you are installing things and passing the relevant environment variable should be enough.

**Comment by 2mf** [comment]
So you are seriously saying, you want to depend on some system libs/headers that don't even exist in many systems even as installable package but has to be installed or put in some special place by hand.

The simplest solution to keep uwsgi installable via pip without special needs, is to either add the header file directly to the git repo or update the install script to pull the greenlet repo in case it is needed.

However, you wouldn't get a +1 if you need to read the documentations on why an install is not working or files are missing.

Please clarify that for me and others who face(d) the same thing.

Thank you.

**Comment by xrmx** [comment]
Il 08/02/2017 12:59, mfranke ha scritto:
> So you are seriously saying, you want to depend on some system libs/headers that
> don't even exist in many systems even as installable package but has to be
> installed or put in some special place by hand.

On which systems greenlet is not packaged?

> The simplest solution to keep uwsgi installable via pip without special needs,
> is to either add the header file directly to the git repo or update the install
> script to pull the greenlet repo in case it is needed.

The dependency on greenlet looks good, but what would be nice to sort out is to 
get the virtualenv include path from python and not by constructing the path by 
hand. If that's not possible we can live with that though.

> However, you wouldn't get a +1 if you need to read the documentations on why an
> install is not working or files are missing.

I think a compiler error telling is not being able to find an header it's pretty 
self explanatory

You forgot to remove the externals dir from your PR.

**Comment by 2mf** [comment]
Sorry about the last comment, please forget about that :-)

I thought I removed that sub repo already...

**Comment by 2mf** [comment]
Ok I'll add a check for VIRTUAL_ENV but if not found, it might be good to default to sys.prefix construct

**Comment by xrmx** [comment]
System python should be already be covered see *plugins/greenlet/uwsgiplugin.py*:
```
CFLAGS = [
    '-I' + sysconfig.get_python_inc(),
    '-I' + sysconfig.get_python_inc(plat_specific=True)
]
```

**Comment by 2mf** [comment]
according to PEP405 `sys.prefix` is the most reliable way, as of VIRTUAL_ENV can not be set if there was no activation of the venv.
So I think, I would leave it that way because gcc would not bother to have the include path a 2nd time.

**Comment by 2mf** [comment]
any other requirements for this pull request?

**Comment by 2mf** [comment]
btw. `sysconfig.get_python_inc()` do not point to right inculde directories e.g. the header of the installed greenlet package. So it is better to use `sys.prefix`.

**Comment by unbit** [comment]
@xrmx seems good to to me, even that explicit check fro greenlet in setup.py is not bad as effectively the greenlet module is something python-specific (and setup.py is python-specific)

If you do not see other problems i will merge it

**Comment by xrmx** [comment]
@unbit merged myself to be sure they got squashed :)

**Comment by cicku** [comment]
so what if system has this library preinstalled?

**Pull request merged**
