### PR TITLE
Drop unused declarations in uwsgi.h

### PR DESCRIPTION
**Pull request by xrmx**
Thanks dholth for spotting these.

Refs #2160

### CODE REVIEW

**Comment by dholth** [comment]
```
        "void manage_opt"
        "find_first_accepting_wsgi_req",
        "find_wsgi_req_by_id",
        "next_wsgi_req",
        "snmp_init",
        "uwsgi_amqp_consume",
        "uwsgi_amqp_consume_queue",
        "uwsgi_cheaper_algo_backlog2",
        "uwsgi_enqueue_message",
        "uwsgi_get_dgram",
        "uwsgi_hooked_parse_dict_dgram",
        "uwsgi_hooks_setns_run",
        "uwsgi_legion_i_am_the_lord",
        "uwsgi_legion_lord_scroll",
        "uwsgi_legion_scrolls",
        "uwsgi_logit_lf_strftime",
        "uwsgi_opt_set_dyn",
        "uwsgi_parse_request",
        "uwsgi_ping_node",
        "uwsgi_proto_base_write_header",
        "uwsgi_response_commit_headers",
        "uwsgi_send_empty_pkt",
        "uwsgi_send_message",
        "uwsgi_simple_request_read",
        "uwsgi_stdin_sendto",
        "uwsgi_string_sendto",
```

Can be checked with the `nm` command e.g.
```
$ nm ./uwsgi | grep recv_cred
000000010002de60 T _uwsgi_recv_cred
000000010002de70 T _uwsgi_recv_cred2
000000010002de80 T _uwsgi_recv_cred_and_fds
```

On Linux use `readelf`. With uwsgi 2.0.17.1:
```
$ readelf -Ws ./uwsgi | grep recv_cred
  1157: 0000000000440f90   351 FUNC    GLOBAL DEFAULT   14 uwsgi_recv_cred
  1253: 00000000004410f0   314 FUNC    GLOBAL DEFAULT   14 uwsgi_recv_cred2
```

**Comment by xrmx** [comment]
@dholth i was looking for the symbols without definitions with the patch applied, I'm on linux, so I have them all :)

**Comment by dholth** [comment]
It's mostly not a platform thing but I'm sure you figured it out

**Comment by dholth** [comment]
This is working well for me.

**Comment by xrmx** [comment]
Thanks for checking!

**Pull request merged**
