### PR TITLE
 Fixed segfault on uems->default is NULL

### PR DESCRIPTION
**Pull request by swuecho**
the format of my change is not quite right, I try to get it right, but failed. 

when uems->defaults is NULL, mongo::fromjson will segfault.

BTW, what does the defaults in uems->defaults mean? thanks.

### CODE REVIEW

**Comment by unbit** [comment]
Honestly i do not remember what defaults is, maybe @WeirdCarrotMonster could help ?

**Comment by WeirdCarrotMonster** [comment]
`uems->defaults` provide default values for emperor attributes. I should have set them to empty dict by default and add few checks for value type.

**Comment by swuecho** [comment]
Thanks. Could you take a look at my pull request or find a better fix？

**Comment by xrmx** [comment]
@swuecho Does this path works for you? https://github.com/xrmx/uwsgi/commit/132a90c5f61e558e043c472670ce253c7c0d480c

**Comment by swuecho** [comment]
@xrmx Should work. Thanks.

**Comment by xrmx** [comment]
@swuecho Fixed in git master 71d657283e8e48dd06dc2cbae4eeb4228f5d3f7d

**Pull request closed without merging**
