### PR TITLE
plugins/gevent: Fix signal handlers

### PR DESCRIPTION
**Pull request by almaslov**
Stop signal watchers only if they were started.

### CODE REVIEW

**Comment by almaslov** [comment]
It should fix https://github.com/unbit/uwsgi/issues/1574

**Comment by unbit** [comment]
Thanks a lot. @xrmx safe for backport

**Comment by neilconway** [comment]
@unbit @xrmx is it possible to backport this fix to the 2.0.x branch?

**Comment by xrmx** [comment]
@neilconway have you checked it's not already there? :)

**Pull request merged**
