### PR TITLE
Fixes #1280 (incorrect cache name handling in uwsgi::cache_set)

### LINKED ISSUE #1280: uwsgi::cache_set() in psgi uses incorrect parameter as cache name
Hi,

Nasty bug when I tried to use named caches:

```diff
--- uwsgi_plmodule.c.orig       2016-05-12 19:37:49.000000000 +0200
+++ uwsgi_plmodule.c    2016-06-09 22:17:44.537846404 +0200
@@ -122,7 +122,7 @@
        if (items > 2) {
                expires = SvIV(ST(2));
                if (items > 3) {
-                       cache = SvPV_nolen(ST(1));
+                       cache = SvPV_nolen(ST(3));
                }
        }
```

Seems no one is using named caches in psgi :)

### PR DESCRIPTION
**Pull request by aldem**

### CODE REVIEW

**Comment by unbit** [comment]
Nice catch :)

**Comment by unbit** [comment]
@xrmx please backport it to stable

**Comment by xrmx** [comment]
@unbit the pull request was against stable branch

**Comment by xrmx** [comment]
Forward ported and pushed both alexander's patches to master.

**Pull request merged**
