### PR TITLE
lua_plugin: new stuff

### PR DESCRIPTION
**Pull request by Darvame**
also can yield and send metatable with __tostring attr;
some cleanups and optimizations;

### CODE REVIEW

**Comment by Darvame** [comment]
I meant built-in, not building, nwm

**Comment by Darvame** [comment]
Don't merge it right now, I need some time to remake a bit the 'uwsgi_api_register_signal' and 'uwsgi_api_register_rpc' functions, coz we can't use luaL_ref() to handle signal/rpc registration

**Comment by Darvame** [comment]
Every lua_State now is using own rpc reference metatable (uwsgi.rpc_ref)

Now I can use new way to register rpc:
```lua
uwsgi.rpc_ref["say hallo"] = function() return "Hallo!"; end
```
is the same as
```lua
uwsgi.register_rpc("say hallo", function() return "Hallo!"; end);
```

but now I can alter rpc_ref of current lua_State without affecting on other lua_States

**Comment by Darvame** [comment]
rpc also supports metatable with __call attr:
```lua
uwsgi.rpc_ref["hello_table"] = setmetatable({[1] = "Hello"}, { __call = function(self)
 return self[1];
end});
```
result:
```lua
"Hello"
```

**Comment by Darvame** [comment]
using uwsgi.signal_ref table for storing signal's functions for current lua_State
must use uwsgi.register_signal() as usual, but now can replace already registered functions in current state via uwsgi.signal_ref table

also add uwsgi.signal() function to test signals

**Comment by Darvame** [comment]
hm, signals ignore target value and use 'worker' by default in 'lazy' mode

**Comment by Darvame** [comment]
uwsgi.cache_set_table:
```lua
local t = { key1 = "value1", key2 = "value2", key3 = "value3" };
uwsgi.cache_set_table(t);
local x = uwsgi.cache_get("key2"); -- x == "value2"
```
uwsgi.cache_get_multi:
```lua
local key1, key2, wrong, key3 = uwsgi.cache_get_multi(nil, "key1", "key2", "wrong_key", "key3");
print(key1, key2, wrong, key3); -- value1 value2 nil value3
```
uwsgi.cache_update_multi:
```lua
uwsgi.cache_update_multi(nil, nil, "key1", "new_value1", "key2", "new_value2");
local key1, key2, wrong, key3 = uwsgi.cache_get_multi(nil, "key1", "key2", "wrong_key", "key3");
print(key1, key2, wrong, key3); -- new_value1 new_value2 nil value3
```
and something like that
overall:
```lua
cache_get_multi(cache(opt), key1, key2(opt), ..., keyn(opt)); -- returns n values
cache_set_table(table, exp_time(opt), cache(opt)); -- returns true (if all ok) or nil and number of bad keys with bad keys (expl: nil, 3, bad_key1, bad_key2, bad_key3)
cache_update_table(table, exp_time(opt), cache(opt)); -- same but update
cache_set_multi(exp_time(opt), cache(opt), key1, value1, key2(opt), value2(opt), ..., keyn(opt), valuen(opt)); -- returns true (if all ok) or nil and numbers of broken key-value pairs (expl: nil 3 4)
cache_update_multi(exp_time(opt), cache(opt), key1, value1, key2(opt), value2(opt), ..., keyn(opt), valuen(opt)); -- same but update
cache_del_multi(cache(opt), key1, key2(opt), ..., keyn(opt)); -- returns true (if all ok) or nil and numbers of bad keys  (expl: nil 3 4) where key3 and key4 hasnt been deleted
cache_exists_multi(cache(opt), key1, key2(opt), ..., keyn(opt)); -- same as cache_get_multi but returns booleans

**Comment by Darvame** [comment]
no more new ideas right now

**Comment by Darvame** [comment]
<h2>Quick Tour</h2>
...

**Comment by Darvame** [comment]
@unbit soooo, do you like my plugin? I've done, I think so

**Comment by unbit** [comment]
Sorry for the long time, but your patch was huge :)

When you have time it would be awesome if you can improve uwsgi-lua docs in the uwsgi-docs repository

Thanks again

**Comment by xrmx** [comment]
@Darvame lua_plugin.c is whitespace damaged, each empty line has spurious tab. FYI Coverity found a couple of new issues in your code opening pull request in a few.

**Pull request merged**
