### PR TITLE
Allow call uwsgi websocket API in other greenlet. （enhanced）

### PR DESCRIPTION
**Pull request by yueyoum**
see the last pull request: #985 

Change: 

1. change `uwsgi_input` to `request_context`.
API change to `uwsgi.request_context()`
`websocket_send/recv` 4 functions keyword argument change to `request_context`

2. add check for argument  `request_context`

### CODE REVIEW

**Comment by unbit** [comment]
Well, nice work. Give me some hour to review it and i will merge. Thanks a lot.

**Comment by yueyoum** [comment]
Hi, due to there is not merge to the uwsgi official version,  we still using the patched version.

Is there any problem in the pull request ?

**Comment by unbit** [comment]
hi, still did not have the time to fully review it. I should be able to complete it soon

**Comment by yueyoum** [comment]
OK,  thanks. :+1:

**Comment by fobdy** [comment]
Currently i have the `uWSGI==2.0.11.2` and got the `'you can call uwsgi api function only from the main callable'` **EXCEPTION** for the `uwsgi.websocket_recv()` call in separate greenlet.

**Comment by xrmx** [comment]
@fodby this has been merged to master not to stable 2.0 branch.

**Comment by fobdy** [comment]
@xrmx Thanks, so i have to build from sources?
Do you know when this will come to the stable branch?

**Comment by fobdy** [comment]
I've built from the sources
```bash
./uwsgi --version
>>> 2.1-dev-1b96a63
```
But this didn't help me ;( I have the same error `you can call uwsgi api function only from the main callable`

**Comment by xrmx** [comment]
@fobdy are you sure you are using it?

note to self: we should probably export a way to print the uwsgi version from the python plugin

**Comment by fobdy** [comment]
Yes i'm sure :) I removed previous uwsgi from pip and then copied uwsgi (with gevent & python `.so`) from my build to the project folder.

**Comment by xrmx** [comment]
@yueyoum any chance you help @fobdy sorting this out please?

**Comment by fobdy** [comment]
I'm using `Python 2.7.5` with `gevent==1.0.2` and `greenlet==0.4.9` with `uwsgi` @1b96a63

**Comment by fobdy** [comment]
i've built then uwsgi with
```bash
python uwsgiconfig.py --build
```
Then just copied it to the my project folder. I'm working under venv. My uwsgi config is

```ini
[uwsgi]
http-socket = 127.0.0.1:9090
wsgi-file = app.py
callable = app
virtualenv = .venv
gevent = 20
master = 1
processes = 1
```

**Comment by yueyoum** [comment]
@fobdy 

Hi,  Be sure your got the latest code. 

```
wang[11:29][~/codes/uwsgi]$ git log | head 
commit f75194caaa34e3b81cbe3798264939d3a3231aca
Author: Riccardo Magliocchetti <riccardo.magliocchetti@gmail.com>
Date:   Fri Oct 23 23:44:56 2015 +0200

    Fix post-buffering option help
    
    See
    https://github.com/unbit/uwsgi/pull/939#issuecomment-118542644
    
    Fix #939
```

then run `make` in uwsgi root folder, 

the version is:
```
./uwsgi --version
2.1-dev-f75194c
```

And then , you can test with the file `tests/websockets_chat_2.py` (chat in browser).

```
./uwsgi --http-socket :9090  --http-raw-body --gevent 100 --module tests.websockets_chat_2
```

it works fine.

can you paste your `app.py` here?  so i can test by myself.

**Comment by fobdy** [comment]
```bash
git pull
git log | head
commit f75194caaa34e3b81cbe3798264939d3a3231aca
Author: Riccardo Magliocchetti <riccardo.magliocchetti@gmail.com>
Date:   Fri Oct 23 23:44:56 2015 +0200

    Fix post-buffering option help

    See
    https://github.com/unbit/uwsgi/pull/939#issuecomment-118542644

    Fix #939
```

```bash
make
./uwsgi --version
>>> 2.1-dev-f75194c
sudo pip install gevent
./uwsgi --http-socket :9090  --http-raw-body --gevent 100 --module tests.websockets_chat_2
```

Opened browser. The test example works fine.

Then running my app causes the same error as i mentioned above.
I try to write some sample case and will paste here.

**Comment by fobdy** [comment]
Here it is. It's a simple echo app with usage of queue and pool.

It raises `SystemError: you can call uwsgi api function only from the main callable` and
`[BUG] current_wsgi_req NOT FOUND !!!` message.

```python
import uwsgi
from gevent.queue import Queue
from gevent.pool import Pool


def producer(queue):
    while True:
        msg = uwsgi.websocket_recv()
        queue.put(msg)


def consumer(queue):
    while True:
        msg = queue.get()
        uwsgi.websocket_send(msg)


def app(env, start_response):
    # complete the handshake
    uwsgi.websocket_handshake(env['HTTP_SEC_WEBSOCKET_KEY'],
                              env.get('HTTP_ORIGIN', ''))
    pool = Pool()
    queue = Queue()
    pool.spawn(producer, queue)
    pool.spawn(consumer, queue)
    pool.join()
```

**Comment by yueyoum** [comment]
@fobdy 

Hi,  the problem is this feature needs pass a **request_context** object to uwsgi websocket api.
SEE the example: https://github.com/unbit/uwsgi/blob/master/tests/websockets_chat_2.py#L42

NOTICE `websocket_send/websocket_recv` can accept a keyword argument named `request_context`,  this context was got from the main greenlet.


AND In uwsgi 2.0+ you can call websocket_handshake without arguments. 

So, I make a few change of your code:
```python
import uwsgi

from gevent.queue import Queue
from gevent.pool import Pool

def producer(queue, request_context):
    while True:
        msg = uwsgi.websocket_recv(request_context=request_context)
        queue.put(msg)

def consumer(queue, request_context):
    while True:
        msg = queue.get()
        uwsgi.websocket_send(msg, request_context=request_context)

def app(env, start_response):
    uwsgi.websocket_handshake()

    request_context = uwsgi.request_context()

    pool = Pool()
    queue = Queue()
    pool.spawn(producer, queue, request_context)
    pool.spawn(consumer, queue, request_context)
    pool.join()

```

Now, it's working!

**Comment by fobdy** [comment]
Oh, w0w!!! @yueyoum LOTS OF THANKS!!!

I think it needs to be given somewhere in the documentation

**Comment by yueyoum** [comment]
yes, great suggestion.

I plan to add more websockets & gevent features,  
then add this in document.

**Pull request merged**
