### PR TITLE
plugins/cgi: adds dontresolve option

### PR DESCRIPTION
**Pull request by Ansuel**
This option permit to call the simbolic link instead of the file the simbolic link points.
All the security check are still done as the simbolic path is passed at the end after all the checks are passed. This is useful if some cgi app are used for multiple function based on the name they are called by.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by rdeioris** [comment]
Thanks, can you move the "int dontresolve;" declaration at the end of the struct ? (not strictly required for plugins but i prefer to maintain ABI compatibility)

**Comment by Ansuel** [comment]
@rdeioris you mean after
`{0, 0, 0, 0, 0, 0, 0},`

Doesn't that needs to be at the end of the struct to set end of it?

**Comment by rdeioris** [comment]
Hi, i mean the field in the uwsgi_cgi struct

**Comment by Ansuel** [comment]
Ow... ok sorry then... Just give me a minute

**Comment by Ansuel** [comment]
Done

**Comment by rdeioris** [comment]
@xrmx safe for backport

**Pull request merged**
