### PR TITLE
Use new style callbacks for pypy

### LINKED ISSUE #1294: Use new style callbacks for the PyPy plugin
Starting from CFFI 1.4 (which means we need to remove support for older PyPy) PyPy is able to call Python directly from C without function pointers.
See http://cffi.readthedocs.io/en/latest/using.html#extern-python-new-style-callbacks
The code currently use `ffi.callback()` which has some overhead.

### PR DESCRIPTION
**Pull request by thedrow**
This is an attempt to fix #1294 quickly...

### CODE REVIEW

**Comment by unbit** [comment]
Still not had the time to check newer pypy features, but this patch is not invasive in the master branch. I am considering to split the pypy plugin from the uWSGI core so we can work on it in an easier way

**Comment by thedrow** [comment]
I haven't tested it yet. It was just for the discussion...
How do I run the tests for thus plugin?

**Comment by thedrow** [comment]
Yes please revert this and reopen the issue.
```
uwsgi --http 0.0.0.0 --pypy-home $(pyenv which pypy) --pypy-lib /Users/omer.katz/.pyenv/versions/pypy-5.3/lib/libpypy-c.dylib
*** Starting uWSGI 2.1-dev-0631f8b (64bit) on [Thu Jul 14 10:16:02 2016] ***
compiled with version: 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31) on 14 July 2016 10:11:05
os: Darwin-15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
nodename: OmerK.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/omer.katz/Documents/uwsgi
detected binary path: /Users/omer.katz/.virtualenvs/uwsgi/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 7168
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0 fd 4
spawned uWSGI http 1 (pid: 70247)
uwsgi socket 0 bound to TCP address 127.0.0.1:60677 (port auto-assigned) fd 3
!!! uWSGI process 70246 got Segmentation Fault !!!
*** backtrace of 70246 ***
0   uwsgi                               0x000000010d7529f0 uwsgi_backtrace + 48
1   uwsgi                               0x000000010d752f33 uwsgi_segfault + 51
2   libsystem_platform.dylib            0x00007fff87a2f52a _sigtramp + 26
3   ???                                 0x00007fc32ac3e750 0x0 + 140476212832080
*** end of backtrace ***
```
I need to find a way to test this first.

**Comment by unbit** [comment]
Reverted. There is currently no way to run python tests from the pypy plugin. I think the best thing to do is writing ad-hoc tests for the pypy plugin

**Pull request merged**
