### PR TITLE
Add log-before option

### PR DESCRIPTION
**Pull request by funkybob**
Add an option to log the pid, remote address, request method and URI early, to aid in debugging.

### CODE REVIEW

**Comment by funkybob** [comment]
This feature was requested by MasterGberry on IRC, in aiding discovering which requests were causing their processes to be OOM killed.

I'm not 100% sure this is the right place for it, but it seems it will be harmless in other cases.

**Comment by mastergberry** [comment]
Confirmed that the above feature would be extremely helpful in debugging an issue with requests not completing due to OOM.

**Comment by unbit** [comment]
Is not it a bit too much ad-hoc ? Maybe it is better to add an hook to that part so the code can go in a plugin.

**Comment by funkybob** [comment]
Yeah, seemed a bit specialist, and I didn't expect it to be accepted :)

Time to learn plugins... yay! :)

**Pull request closed without merging**
