### PR TITLE
Fix readline support in python3 when working interactively

### PR DESCRIPTION
**Pull request by asottile**
See #1309 for description.

This is probably not a correct solution, but figured I'd open this for discussion.

### CODE REVIEW

**Comment by unbit** [comment]
Unfortunately this break logging in python3

**Comment by asottile** [comment]
Would it be acceptable to disable this when stdin is a tty?

Could you elaborate on "breaks logging"? I have a feeling you're referring to the (bug?) in python3 that stderr is buffered.

**Comment by asottile** [comment]
I've clarified the comment and updated my commit to only run the reassignment when it is a non-tty.  This fixes my usecase and seems to be the least invasive -- let me know what you think :D

**Comment by asottile** [comment]
ping: 1 week, this is blocking some development internally (we're considering a private fork)

**Comment by rdeioris** [comment]
Unfortunately every decision we make in this topic will end in mess for someone else (and honestly i agree that the current python3 behaviour is more near to a bug than a feature). I continue to see funny uses/abuses of stdout/stderr so i would be more inclined to add a python3 plugin specific option to allow the user/admin to choose the behaviour that fit best to him/her.  It is a fast thing to do (you already covered 90% of the problem), but if you are in super-hurry i strongly suggest the 'private fork way'. @xrmx any opinion on the topic ?

**Comment by xrmx** [comment]
Adding this as a specific option for the python plugin looks good to me

**Comment by asottile** [comment]
To be honest, I was pretty surprised that uwsgi attempts to "solve" this.  As bad as this "feature" of python3 is, it should really be up to the application to decide whether it wants that behaviour or not.  And uwsgi's monkeypatching of `sys` to change the streams (and put stdout to stderr?) was certainly surprising!  If `uwsgi`'s python plugin aims to be a simple wrapper around the python interpreter, I certainly expect it to act the same as `python` :)  (which is why I initially suggested this patch: https://github.com/unbit/uwsgi/issues/1309#issuecomment-230048415)

**Comment by unbit** [comment]
Unfortunately the python3 choice, broke advanced loggers (syslog mainly), this is why that part is here. I think adding a dedicated option for python3 is the best thing to do. Expect an official patch (with your credits) soon

**Comment by asottile** [comment]
Any timeline on when this or something like this will reach mainline?

**Comment by unbit** [comment]
By the end of this week :) thanks again

**Comment by unbit** [comment]
@xrmx safe for backporting too.

@asottile After a second review of your patch it looks like it does not need a specific option to enable it, as your proposed approach is the saner one. Thanks a lot, and sorry for the late

**Comment by asottile** [comment]
\o/ What's uwsgi's release cycle like (wondering how long we want to plan to maintain a fork)

**Pull request merged**
