### PR TITLE
Work around some inconvenience in PSGI specs for out of PSGI protocols

### PR DESCRIPTION
**Pull request by jef-sure**
This patch should close issue #1343

### CODE REVIEW

**Comment by jef-sure** [comment]
av_top_index() was introduced only in perl 5.18. So, I replaced it with old av_len()

**Comment by unbit** [comment]
@xrmx safe for backport

**Comment by unbit** [comment]
@jef-sure thanks a lot

**Comment by xrmx** [comment]
*cough* squash next time please *cough*

**Comment by jef-sure** [comment]
I think it's better not to close $env->{'psgix.io'} on PSGI cancel. Unfortunately, it takes time to go through unfamiliar uwsgi sources. That's why one more patch.

**Pull request merged**
