### PR TITLE
fix building with musl libc

### PR DESCRIPTION
**Pull request by ncopa**
A set of patches needed to make uwsgi build on musl libc, which is fairly strict.

It is compile tested with musl libc and uClibc.

### CODE REVIEW

**Comment by xrmx** [comment]
@ncopa any chance you can rebase on top of master?
 My only concern is about "always define _GNU_SOURCE for linux" where you are defining GNU_SOURCE only for __linux__, wondering how that change does affect gnu/kFreeBSD

**Comment by ncopa** [comment]
It is now rebased against current master.

Good catch wrt gnu/kFreeBSD. I created a vm with debian kFreeBSD and indeed, it did break build there. I changed the `#ifdef __linux__` to `#if defined(__linux__) || defined(__GNUC__)`.
I also added an `#undef _GNU_SOURCE` at the end as _GNU_SOURCE causes problems for Python.h as mentioned earlier.

I have compile tested it in both alpine linux (musl libc) and debian kbsd. It builds at least.

**Comment by xrmx** [comment]
@ncopa thanks!
@unbit probably a good time to merge this and catch any build breakage?

**Comment by a-tal** [comment]
hello. I tried building @ncopa's branch today, and while it does compile in alpine with musl, it errors on start with `unable to set PTHREAD_PRIO_INHERIT`.

:+1: for musl support though, let me know if you need anything else

**Comment by xrmx** [comment]
@a-tal thanks for testing!
Indeed pthread_mutexattr_setprotocol is not supported on musl:
http://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_mutexattr_setprotocol.c
What about undefining EOWNERDEAD for musl?, see lock.c line 49

**Comment by ncopa** [comment]
> What about undefining EOWNERDEAD for musl?, see lock.c line 49

I don't like that. What if future version of musl has support for PTHREAD_PRIO_INHERIT?

Also the PTHREAD_PRIO_INHERT will only prevent priority inversion when SCHED_FIFO or SCHED_RR is used. I could not find anything in code indicating that real-time priority threads is used anywhere, so I believe this could be a non-fatal error.
```diff
diff --git a/core/lock.c b/core/lock.c
index 20935b5..d1005bd 100644
--- a/core/lock.c
+++ b/core/lock.c
@@ -97,7 +97,9 @@ retry:
        if (uwsgi_pthread_robust_mutexes_enabled) {
                if (pthread_mutexattr_setprotocol(&attr, PTHREAD_PRIO_INHERIT)) {
                        uwsgi_log("unable to set PTHREAD_PRIO_INHERIT\n");
-                       exit(1);
+                       /* PTHREAD_PRIO_INHERIT will only prevent priority
+                          inversion when SCHED_FIFO or SCHED_RR is used, so
+                          this is non-fatal */
                }
                if (pthread_mutexattr_setrobust(&attr, PTHREAD_MUTEX_ROBUST)) {
                        uwsgi_log("unable to make the mutex 'robust'\n");
```

**Comment by ncopa** [comment]
While at it, we could make a runtime error when setting robust make it fall back to standard pthread mutexes:
```diff
diff --git a/core/lock.c b/core/lock.c
index 20935b5..476a35e 100644
--- a/core/lock.c
+++ b/core/lock.c
@@ -97,11 +97,14 @@ retry:
        if (uwsgi_pthread_robust_mutexes_enabled) {
                if (pthread_mutexattr_setprotocol(&attr, PTHREAD_PRIO_INHERIT)) {
                        uwsgi_log("unable to set PTHREAD_PRIO_INHERIT\n");
-                       exit(1);
+                       /* PTHREAD_PRIO_INHERIT will only prevent priority
+                          inversion when SCHED_FIFO or SCHED_RR is used, so
+                          this is non-fatal */
                }
                if (pthread_mutexattr_setrobust(&attr, PTHREAD_MUTEX_ROBUST)) {
-                       uwsgi_log("unable to make the mutex 'robust'\n");
-                       exit(1);
+                       uwsgi_log("!!! unable to make the mutex 'robust'\n");
+                       uwsgi_log("!!! falling back to standard pthread mutexes !!!\n");
+                       uwsgi_pthread_robust_mutexes_enabled = 0;
                }
        }
 #endif
```

**Comment by xrmx** [comment]
Il 06/08/2015 11:07, ncopa ha scritto:
> While at it, we could make a runtime error when setting robust make it fall back
> to standard pthread mutexes:

I don't think this change of behaviour should be made in this patchset, 
especially if it's changing behaviour on other configurations. I'd just go with 
the minimal changes to get uwsgi compile with musl and then we can reason about 
other changes.

**Comment by bodgit** [comment]
Is there any plan to fix the `PTHREAD_PRIO_INHERIT` problem on musl? Compiling from master (there doesn't seem to be a release with these changes in yet) on Alpine Linux gets a binary provided I omit the ugreen plugin however I'm in the same boat as @a-tal in that the uwsgi binary won't actually run due to this fatal error.

**Comment by xrmx** [comment]
@bodgit could you please check if applying this changes https://github.com/unbit/uwsgi/pull/522#issuecomment-128296571 works for you?

**Comment by ncopa** [comment]
@bodgit I am not aware of any plans to implement `PTHREAD_PRIO_INHERIT`.

Returning `ENOTSUP` is also perfectly [valid](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutexattr_getprotocol.html#tag_16_443_05).

**Comment by bodgit** [comment]
@xrmx Yes, making the change referenced in the comment and removing the `exit(1);` to make the `PTHREAD_PRIO_INHERIT` error non-fatal allows the binary to start up and so far I've not seen any further problems.

**Comment by ncopa** [comment]
Why is the `PTHREAD_PRIO_INHERIT` there in the first place?

**Comment by bodgit** [comment]
Is it worth creating a new PR with these additional changes so that it can be discussed separately?

**Comment by xrmx** [comment]
@bodgit sure, i'd change the code to not return error only if ENOTSUP is returned as suggested by @ncopa. And keep his comment, maybe adding explicitly that musl does not implement that. Thanks.

**Comment by bodgit** [comment]
Sure, will do.

**Pull request merged**
