### PR TITLE
Add bindings to the Python API

### PR DESCRIPTION
**Pull request by Shir0kamii**
Hi,

First, I'm sorry for the inconvenience about closing a PR and opening another one. I now understand that it's only noise for you and won't do it again.

Then, the PR stuff. It adds two new functions to the Python API. Each one is about identifying a process. One for spoolers, and one for mules.

In a mule process, you can call `uwsgi.mule_file()` and get the patch applied to the mule (or None if there was no patch applied). If you give the id of a mule to the function, it will give you the patch applied to that mule, even if you're not in a mule process.

In a spooler process, you can call `uwsgi.spooler_dir()` and get the directory the spooler is monitoring. I didn't add the ability to retrieve spooler directory by id, since spooler doesn't have ids and I don't know if I should simulate an ID, by enumerating the spoolers. If you prefer me to implement it, just ask.

Again, I will add these entries to uwsgi-doc soon if it's merged. And I hope it will!

Cheers

### CODE REVIEW

**Comment by xrmx** [comment]
Patches looks good to me, but what about adding a couple of tests? :)

**Comment by Shir0kamii** [comment]
@xrmx Sorry for the wait, I finally took the time to make these tests. Is it okay for you ?

**Comment by Shir0kamii** [comment]
@xrmx @unbit Could you please take a decision so we can close this PR?

**Comment by unbit** [comment]
Thanks a lot and sorry for the huge late.

**Pull request merged**
