### PR TITLE
Be more helpful when a request has an unknown modifier1

### PR DESCRIPTION
**Pull request by akx**
Adds a list of "well-known" modifier1 values and changes the

> -- unavailable modifier requested: %d --

message to add a hint about which plugin might be needed to
fix the situation.

(Missing plugins seems to be a common enough problem.)

### CODE REVIEW

**Comment by akx** [comment]
@unbit Seems this PR has gone stale -- do you think it could get merged if I rebase it?

**Comment by unbit** [comment]
the mapping of modifiers is becaming pretty "opaque" recently with the proliferation of third party plugins. They are mainly a suggestions, and lot of users tend to overwrite the zero one to simplify setups. I do not know if it is a good idea to add hardcoded values. I leave this open for futher discussion.

Thanks as always

**Comment by akx** [comment]
Well, if I add support for the modifier remap table here?

(Aside: I feel it would be a good idea to have a table of known "contrib"/external modifier1s too, to avoid conflicts (even if they are eventually inevitable).)

**Comment by xrmx** [comment]
Not scrictly related to the patch but speaking of plugins, what about adding a plugins registry? Something like a json hosted in this repo that lists plugin name, description, modifier, url, whatever. Plus some script that add automatically the bundled ones. We can then add a human friendly js app on top.

**Comment by akx** [comment]
Closing to clean up my PR list ✌️

**Pull request closed without merging**
