### PR TITLE
Updated GridFS plugin

### PR DESCRIPTION
**Pull request by WeirdCarrotMonster**
Fixes https://github.com/unbit/uwsgi/issues/882

I haven't implemented pooling, but plugin itself works. I think it would be better to have working version now.

### CODE REVIEW

**Comment by unbit** [comment]
I am a bit unsure about forcing c++11, is it truly required ?

**Comment by WeirdCarrotMonster** [comment]
No, i only use it for unique_ptr. It can be replaced with auto_ptr, but as far as i know auto_ptr is deprecated.

**Comment by unbit** [comment]
Yes, auto_ptr is deprecated, at this point i think we can merge it as-is

**Comment by unbit** [comment]
Merged, thanks again

**Pull request closed without merging**
