### PR TITLE
Support Brotli in static-gzip path

### PR DESCRIPTION
**Pull request by funkybob**
Allow pre-compressed Brotli static files.

### CODE REVIEW

**Comment by xrmx** [comment]
Any chance you can convince your editor to don't fix the whitespace if you don't modify the code?

**Comment by funkybob** [comment]
Sorry, reflex action on my part to make it easier to read and work on (and a touch of OCD on my part :)


On 14 June 2017 6:36:53 AM AEST, Riccardo Magliocchetti <notifications@github.com> wrote:
>Any chance you can convince your editor to don't fix the whitespace if
>you don't modify the code?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/unbit/uwsgi/pull/1553#issuecomment-308240913

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xrmx** [comment]
Well it's fine if you separate the commit fixing whitespace from the rest so one can look only at the modified lines.

**Comment by funkybob** [comment]
Of course, there's always appending ?w=1 to the file view URL :)

On 14 June 2017 6:41:46 AM AEST, Riccardo Magliocchetti <notifications@github.com> wrote:
>Well it's fine if you separate the commit fixing whitespace from the
>rest so one can look only at the modified lines.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/unbit/uwsgi/pull/1553#issuecomment-308242140

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by funkybob** [comment]
Are you happy to use github's secret ?w=1  or should I re-build this branch?

**Comment by xrmx** [comment]
Yeah, we can live with that.

**Comment by unbit** [comment]
Sorry for the late :) @xrmx it should be safe for backport, but take into account that i discovered last week what brotli is :)

**Pull request merged**
