### PR TITLE
Add logic option if-hostname-match

### PR DESCRIPTION
**Pull request by Shir0kamii**
Hi,

I added a new logic option to uwsgi called if-hostname-match that take a regex and evaluate to true if the hostname match the regex.

In my team, we have multiple servers running uwsgi and setting several if-hostname condition blocks is rather long, so it would be great if we could just use a regex.

What do you think about this ?

### CODE REVIEW

**Comment by Lujeni** [comment]
+1 :cactus: 
@Shir0kamii can you add a configuration example of this feature pls?

**Comment by Shir0kamii** [comment]
Of course, here is a simple example of configuration using if-hostname-match : 

```
…
threads = 10

if-hostname-match = prod
    threads = 20
end-if = true
…
```

If you have several servers used for production containing "prod" in their hostname, you can use these configuration lines to use more threads on production servers.

**Comment by btall** [comment]
:+1:

**Comment by ramnes** [comment]
Definitely :+1:

**Comment by xrmx** [comment]
@Shir0kamii thanks for the patch! Could you please tell to your coworkers that +1 are even more annoying than usual if they came from people of the same company? :)

**Comment by xrmx** [comment]
From a quick look the patch is fine, we may want in future to try to reuse some code for similar matches though. After this go in it would be nice to update uwsgi-docs with this and the spooler api addition.

**Comment by xrmx** [comment]
Well in this case, why one cannot be the negation of the other one? Like:
```
int uwsgi_logic_opt_if_not_hostname_match(char *key, char *value) {
   return !uwsgi_logic_opt_if_hostname_match(key, value);
}
```

**Comment by ramnes** [comment]
Alright, fair enough. Next time I'll make a fake account so I can +1 great features without being caught!

**Comment by Shir0kamii** [comment]
Of course I will update the documentation as soon as I can.

I'll try to clean up the code the next time I work on it. For now, spaces and tabulations are mixed in the codebase, should I replace spaces with tabulation or the inverse ? Also, do you prefer a specific standard for the code ?

For example, the goto directives. I found some in the code (note that it's inconsistent with most of the codebase) and it's usually considered bad practice to use them. So should I change them into loop when I encounter one or is there a good reason for them to be there ?

**Comment by unbit** [comment]
@Shir0kamii goto's in c are not a bad practice (it is a common misconception), you will find tons of them in the linux kernel, nginx, and friends :)

**Comment by Darvame** [comment]
They should add "like" feature for pull requests

**Comment by Shir0kamii** [comment]
@unbit I didn't know, my bad.

**Comment by unbit** [comment]
@xrmx the feature is interesting, my only fear is in the use of the regex header that is not ubiquitous. I would prefer the usage of uWSGI pcre api. And yes, generalizing the feature (to allow regexps in other if-based opts) would be cool but would require re-writing some of the internal api. @Shir0kamii would you like to try refactor it using pcre api ?

```c
uwsgi_regexp_build(char *regexp, pcre ** pattern, pcre_extra ** pattern_extra);
uwsgi_regexp_match(pcre * pattern, pcre_extra * pattern_extra, char *subject, int length);
```

**Comment by Shir0kamii** [comment]
@unbit I tried what you asked, please tell me if it seems good to you.

Also I added a function that should be useful if you want to implement other options using regexp. It should reduce the code duplication.

**Comment by unbit** [comment]
@Shir0kamii nice work. Even the api addition seems a handy thing. I will merge it and backport to 2.0 too. Thanks

**Comment by Shir0kamii** [comment]
@unbit Thank you ! Could you please backport the spooler feature at the same time ?

**Comment by unbit** [comment]
@Shir0kamii which one ?

**Comment by Shir0kamii** [comment]
@unbit I'm talking about #1118

**Pull request merged**
